FROM node:lts-alpine as build-stage
WORKDIR /app

COPY package*.json ./

RUN npm install -g @quasar/cli && npm install -g @vue/cli && npm install -g @vue/cli-init
RUN npm install
COPY . .
RUN quasar build


FROM nginx:stable-alpine as prod-stage

RUN mkdir /app && mkdir -p /app/static-pages
COPY --from=build-stage /app/dist/spa /app
COPY nginx.conf /etc/nginx/nginx.conf
