from sqlalchemy import Column, Integer, String, Float, DateTime, Text
from datetime import datetime
from database import Base


class Member(Base):
    __tablename__ = "members"

    id = Column(Integer, primary_key=True, index=True)
    full_name = Column(String(255), nullable=False)
    father_spouse_name = Column(String(255), nullable=True)
    date_of_birth = Column(String(10), nullable=True)
    gender = Column(String(50), nullable=True)
    marital_status = Column(String(50), nullable=True)
    place = Column(String(255), nullable=True)
    adhar_number = Column(String(12), nullable=True, unique=True)
    pan_number = Column(String(10), nullable=True)
    customer_photo = Column(Text, nullable=True)
    primary_mobile_number = Column(String(20), nullable=False, unique=True)
    alternate_contact_number = Column(String(20), nullable=True)
    email_address = Column(String(255), nullable=True)
    current_address = Column(Text, nullable=True)
    pincode = Column(String(10), nullable=True)
    residence_type = Column(String(50), nullable=True)
    years_at_current_residence = Column(Integer, nullable=True)
    permanent_address = Column(Text, nullable=True)
    occupation_type = Column(String(100), nullable=True)
    employer_business_name = Column(String(255), nullable=True)
    work_address = Column(Text, nullable=True)
    designation = Column(String(100), nullable=True)
    monthly_gross_income = Column(Float, nullable=True)
    monthly_net_income = Column(Float, nullable=True)
    total_work_experience = Column(String(50), nullable=True)
    existing_active_loans = Column(Integer, nullable=True)
    total_monthly_emi = Column(Float, nullable=True)
    number_of_dependents = Column(Integer, nullable=True)
    account_holder_name = Column(String(255), nullable=True)
    bank_name = Column(String(255), nullable=True)
    account_number = Column(String(50), nullable=True)
    ifsc_code = Column(String(20), nullable=True)
    branch_name = Column(String(255), nullable=True)
    guarantor_name = Column(String(255), nullable=True)
    guarantor_relationship = Column(String(100), nullable=True)
    guarantor_contact_number = Column(String(20), nullable=True)
    guarantor_kyc_id = Column(String(50), nullable=True)
    status = Column(String(1), default='A', nullable=False)
    del_mark = Column(String(1), default='N', nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_by = Column(String(255), nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    updated_by = Column(String(255), nullable=True)
