from sqlalchemy import Column, Integer, String, Float, DateTime, Date, Numeric
from database import Base


class ReportsView(Base):
    __tablename__ = "reports"
    __table_args__ = {'extend_existing': True}

    loan_id = Column(Integer, primary_key=True, index=True)
    loan_number = Column(String(255), index=True)
    loan_amount = Column(Float)
    interest_amount = Column(Float)
    total_loan_amount = Column(Float)
    emi_day = Column(String(50))
    loan_start_date = Column(Date)
    repayment_frequency = Column(String(50))
    loan_tenure = Column(Integer)
    interest_rate = Column(Float)
    processing_fees = Column(Float)
    insurance_fees = Column(Float)
    other_fees = Column(Float)
    loan_status = Column(String(50))
    application_date = Column(Date)
    field_officer_id = Column(String(255))
    group_id = Column(Integer)
    group_name = Column(String(255))
    loan_member_id = Column(Integer)
    member_id = Column(Integer)
    member_name = Column(String(255))
    member_phone = Column(String(255))
    member_place = Column(String(255))
    member_loan_amount = Column(Numeric(10, 2))
    member_collected = Column(Numeric(10, 2))
    member_pending = Column(Numeric(10, 2))
    member_advance = Column(Numeric(10, 2))
    billing_id = Column(Integer)
    billing_code = Column(String(50))
    billing_amount = Column(Numeric(10, 2))
    billing_type = Column(String(20))
    billing_date = Column(DateTime)
    emi_id = Column(Integer)
    emi_date = Column(Date)
    emi_amount = Column(Numeric(10, 2))
    emi_status = Column(String(50))
    emi_delay = Column(String(50))
    emi_label = Column(String(50))
    paid_emis = Column(Integer)
    pending_emis = Column(Integer)
    overdue_emis = Column(Integer)
    total_emis = Column(Integer)
    total_paid_emi_amount = Column(Numeric(10, 2))
    total_pending_emi_amount = Column(Numeric(10, 2))
    total_overdue_emi_amount = Column(Numeric(10, 2))
    total_interest = Column(Numeric(10, 2))
    total_processing_fees = Column(Numeric(10, 2))
    total_insurance_fees = Column(Numeric(10, 2))
    total_other_fees = Column(Numeric(10, 2))
    total_payments = Column(Numeric(10, 2))
    created_at = Column(DateTime)
    created_by = Column(String(255))
    updated_at = Column(DateTime)
    updated_by = Column(String(255))
